apiVersion: v2
appVersion: v1.17.2
name: velero
version: 0.8.1
description: Deploys Velero
home: https://gitlabee.dt.renault.com/digital-cloud-platform/infra/helm-charts/velero.git
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
sources:
  - https://github.com/vmware-tanzu/velero
maintainers:
  - name: Baha-Eddine BOUKHZAR
    email: baha-eddine.boukhzar-extern@renault.com
  - name: Bilel Ismail
    email: bilel.ismail-extern@renault.com
dependencies:
  - name: velero
    version: 11.3.2
    repository: https://vmware-tanzu.github.io/helm-charts
  - name: workload-identity
    version: 0.4.3
    repository: oci://europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
    alias: workloadidentity
    condition: tags.configConnector.workloadIdentity

  - name: iam-policy-member
    version: 1.2.0
    repository: oci://europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
    alias: iampolicymember
    condition: tags.configConnector.iamPolicyMember

  - name: iam-custom-role
    version: 0.1.1
    repository: oci://europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
    alias: iamcustomrole
    condition: tags.configConnector.iamCustomRole
  - name: bucket
    version: 0.1.2
    repository: oci://europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
    alias: gcpbucket
    condition: tags.configConnector.gcpBucket
