velero:
  image:
    repository: docker.io/velero/velero
    tag: v1.18.0
    pullPolicy: IfNotPresent
    imagePullSecrets: []
gateway-helm:
  enabled: true
  image:
    repository: docker.io/envoyproxy/envoy
    tag: v1.7.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80